# Generated by Django 4.0.3 on 2022-06-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acc_name', models.CharField(max_length=120)),
                ('acc_number', models.BigIntegerField()),
                ('branch', models.CharField(max_length=120)),
                ('ifsc', models.BigIntegerField()),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
                ('pin', models.IntegerField()),
            ],
            options={
                'db_table': 'sellerreg',
            },
        ),
    ]
