# Generated by Django 4.0.3 on 2022-06-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sellerregistration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerregistration',
            name='email',
            field=models.CharField(default=10, max_length=120),
            preserve_default=False,
        ),
    ]
