# Generated by Django 4.0.3 on 2022-06-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sellerregistration_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'adminlogin',
            },
        ),
    ]
